
# PAPI: %cultpursuitresource_next_event%
# permission: cultpursuitresources.admin

settings:
  items:
    maxEventItems: 2 # Сколько максимум будет доступно предметов для продажи
  event:
    time: 30m # Сколько по времени будет идти событие
    rewards: # Список наград для топеров
      1: # Позиция в топе
        commands:
          - 'eco give {player} 1000' # Команды выполняются от имени консоли
      2-3: # Позиция в топе от 2 до 3
        commands:
          - 'eco give {player} 500'
    start-times: # Часы, когда событие будет автоматически начинаться
      - '19:00'

messages:
  event:
    top-format: " &8- &6{number}. &a{player} &f- &e{sales} &fпродаж"
    start:
      - ''
      - '&f           &6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ                  &f'
      - '&f &fСобытие по продаже предметов у скупщика &aначалось&f!'
      - '&f &fПоспеши продать как можно больше предметов, чтобы'
      - '&f       &fполучить ценные награды                   &f'
    end:
      - '&f           &6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ                  &f'
      - '&f &fСобытие по продаже предметов у скупщика &cзавершилось&f!'
      - '&f &fСписок игроков, которые заняли &eТоп-3&f:'
      - ' {top}'
      - ''
      - '&f &8- &fВы заняли &e{player-top} &fместо среди игроков'
  sell:
    dont-have-items: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &cУ вас недостаточно предметов для продажи"
    sell: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &fВы успешно продали &a{item} &7(x{amount}) &fпо цене &e{price}"
  no-permission: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &cУ вас недостаточно прав"
  commands:
    help:
      - ''
      - '&f           &6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ                  &f'
      - ' &8- &fНачать событие: &e/cultpursuitresources force'
      - ' &8- &fЗавершить событие: &e/cultpursuitresources end'
      - ''
    force:
      already-active: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &cСобытие уже активно"
      force: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &fСобытие было успешно начато"
    end:
      no-active: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &cСобытие не активно"
      end: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ &8| &fСобытие было успешно завершено"

inventories:
  event-menu:
    title: "&8Событие скупщика"
    structure:
      - '. . . . i . . . .'
      - '. . . . . . . . .'
      - '. x x x x x x x .'
      - '. x x x x x x x .'
      - '. x x x x x x x .'
      - '. . b . c . n . .'
    items:
      not-active:
        slot: 22
        custom: false
        displayName: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ"
        lore:
          - ''
          - '&fСобытие скупщика ещё не началось,'
          - '&fприходите позже!'
          - ''
          - ' &fВремя, когда проходит событие &7(МСК):'
          - ' &8- &a12:00 '
        item:
          material: "BARRIER"
          head: ""
      default:
        symbol: 'x'
        displayName: "&a{item} &8| &fПродаж: &e{current-sell}"
        lore:
          - ''
          - ' &8- &fЦена: &e{price}'
          - ' &8- &fМножитель: &ex{multiplier}'
          - ''
          - ' &8- &eНажмите ЛКМ, чтобы продать 1 предмет'
          - ' &8- &eНажмите ПКМ, чтобы продать 64 предмета'
          - ' &8- &eНажмите КОЛЁСИКО, чтобы продать все предметы'
      info:
        custom: true
        symbol: 'i'
        displayName: "&6ᴄᴜʟᴛᴘᴜʀѕᴜɪᴛʀᴇѕᴏᴜʀᴄᴇѕ"
        lore:
          - ''
          - '&fВ данном событии Вам и остальным игрокам'
          - '&fнеобходимо соревноваться, кто сможет продать'
          - '&fбольше предмтеов, представленных ниже, за'
          - '&fэти &a30 минут&f, чтобы получить ценные награды!'
        item:
          material: "BOOK"
          head: ""
      close:
        custom: true
        symbol: 'c'
        displayName: "&cЗакрыть"
        item:
          material: "BARRIER"
          head: ""
